# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Hare - Front-end UX developer
email: tom@hare.me
description: >-
  Tom Hare, front-end UX developer based in Karlsruhe, Germany.
baseurl: ""
url: "https://colourgarden.net"
lang: en_GB
google_analytics: UA-11875283-1
twitter:
  username: colourgarden
  card: summary
social:
  name: Tom Hare
  links:
    - https://twitter.com/colourgarden
    - https://www.linkedin.com/in/tom-h-5399b776
    - https://github.com/colourgarden

collections:
  - work

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
